### ISSUE TITLE
RTD build is broken

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#123]
This just happened
https://readthedocs.org/projects/pangeo-forge/builds/13685699/

```
Running Sphinx v2.4.4
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: [new config] 12 added, 12 changed, 0 removed
reading sources... [  8%] bakeries
reading sources... [ 16%] execution
reading sources... [ 25%] file_patterns
reading sources... [ 33%] index
reading sources... [ 41%] recipe_box
reading sources... [ 50%] recipes
reading sources... [ 58%] storage
reading sources... [ 66%] tutorials/cmip6-recipe
WARNING: Notebook load failed for file_patterns: default_parser() got an unexpected keyword argument 'disable_syntax'
/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/checkouts/latest/docs/recipe_box.md:14: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
WARNING: Cannot treat a function defined as a local function: "pangeo_forge_recipes.recipes.XarrayZarrRecipe"  (use @functools.wraps)
WARNING: Cannot treat a function defined as a local function: "pangeo_forge_recipes.storage.FSSpecTarget"  (use @functools.wraps)
WARNING: Cannot treat a function defined as a local function: "pangeo_forge_recipes.storage.FlatFSSpecTarget"  (use @functools.wraps)
WARNING: Cannot treat a function defined as a local function: "pangeo_forge_recipes.storage.CacheFSSpecTarget"  (use @functools.wraps)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/myst_nb/parser.py", line 69, in parse
    md_parser, env, tokens = nb_to_tokens(ntbk)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/myst_nb/parser.py", line 89, in nb_to_tokens
    md = default_parser().disable("front_matter", ignoreInvalid=True)
TypeError: default_parser() missing 1 required positional argument: 'config'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-forge/envs/latest/lib/python3.7/site-packages/myst_nb/parser.py", line 89, in nb_to_tokens
    md = default_parser().disable("front_matter", ignoreInvalid=True)
TypeError: default_parser() missing 1 required positional argument: 'config'
The full traceback has been saved in /tmp/sphinx-err-d7rlb5xb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Smells like a dependency issue. Did one of our dependencies recently make a new release that broke our configuration?

**Comment by rabernat** [comment]
@cisaacstern - if you want to look at this, the steps would be as follows:

- Set up an isolated virtual environment / conda environment based on the documentation's [requirements.txt](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/docs/requirements.txt)
- Try to build the docs
    ```bash
    cd docs/
    make html
    ```
- See if you can reproduce the error
- Follow to stack trace to see if you can figure out the problem and fix it
- If not, try pinning the doc dependencies in the environment to some earlier versions to see if the problem goes away
