### ISSUE TITLE
`copy_pruned` fails when `nkeep` < `inputs_per_chunk`

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#279]
I needed to push https://github.com/pangeo-forge/registrar/pull/1/commits/fa6bc0d8960f4917d3b08501d3a22bfa4e072023 to get `copy_pruned` to work for the OISST recipe without raising

```python
---------------------------------------------------------------------------
Task 'store_chunk[0]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 861, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/utilities/executors.py", line 323, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/charlesstern/Dropbox/pangeo/registrar/registrar/flow.py", line 38, in wrapper
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py", line 499, in store_chunk
    write_region, conflicts = region_and_conflicts_for_chunk(config, chunk_key)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py", line 232, in region_and_conflicts_for_chunk
    target_grid = ChunkGrid.from_uniform_grid(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pangeo_forge_recipes/chunk_grid.py", line 45, in from_uniform_grid
    assert (
AssertionError: invalid chunksize 20 and dimsize 2
```
I'm surprised that we didn't hit this earlier, but it seems like an actual bug (rather than user error). Basically, the un-pruned recipe defines `inputs_per_chunk=20` but the pruned recipe only has a total of 2 input files, and so fails when `region_and_conflicts_per_chunk` is called within `store_chunk`.

_Originally posted by @cisaacstern in https://github.com/pangeo-forge/registrar/issues/1#issuecomment-1033107536_

**Comment by rabernat** [comment]
Looks similar to https://github.com/pangeo-forge/pangeo-forge-recipes/issues/200
