### ISSUE TITLE
mamba is broken in CI: "local variable 'transaction' referenced before assignment"

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#283]
See e.g. https://github.com/pangeo-forge/pangeo-forge-recipes/runs/5189006101?check_suite_focus=true

```
Updating 'pangeo-forge-recipes' env from conda create (simple)...
  /usr/share/miniconda3/condabin/mamba create --name pangeo-forge-recipes
  Warning: 
  # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
  
      Traceback (most recent call last):
        File "/usr/share/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
          return func(*args, **kwargs)
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 934, in exception_converter
          raise e
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
          exit_code = _wrapped_main(*args, **kwargs)
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 882, in _wrapped_main
          result = do_call(args, p)
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 748, in do_call
          exit_code = create(args, parser)
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 624, in create
          return install(args, parser, "create")
        File "/usr/share/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line [577](https://github.com/pangeo-forge/pangeo-forge-recipes/runs/5188994731?check_suite_focus=true#step:4:577), in install
          if not transaction.prompt():
      UnboundLocalError: local variable 'transaction' referenced before assignment
```

**Comment by rabernat** [comment]
Looks like this is being tracked in https://github.com/mamba-org/mamba/issues/1459

**Comment by wolfv** [comment]
Should be all fixed now!
