### ISSUE TITLE
Inconsistent sequence lengths between indices in XarrayZarrRecipe

### ISSUE THREAD

**Issue by bask0** [pangeo-forge/pangeo-forge-recipes#380]
## Version

* pangeo_forge_recipes v0.9.0
* python 3.10

## Problem description

Hi, I am trying to merge a couple of ERA5 datasets using the XarrayZarrRecipe. The data has hourly resolution and is packed into monthly files. When I run the recipe, the following error occurs:

```
ValueError: Inconsistent sequence lengths between indices [1 3 0] of the concat dim.
```

The difference in the sequence lengths is obviously due to the varying number of days in different months. I found [a tutorial](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/tutorials/xarray_zarr/netcdf_zarr_sequential.html) that mentions this issue:

* _"Inconsistent size of data in input files: This means we have to scan each input file and cache its metadata before we can start writing the target.'"_
* _"A key property of this recipe is `nitems_per_input=None`, which triggers caching of input metadata."_

So I do exactly this, I use the default `nitems_per_input=None` in `ConcatDim`, and I cache the inputs ( `XarrayZarrRecipe(..., cache_inputs=True)`), see full code below.

## Error message

We can see how each file is cached, but after the caching I get an error:

```
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Caching input 'Index({DimIndex(name='time', index=0, sequence_len=4, operation=<CombineOp.CONCAT: 2>), DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>)})'
pangeo_forge_recipes.storage - INFO - Caching file 'preproc/t2m.hourly.1460.1140.01.2004.nc'
pangeo_forge_recipes.storage - INFO - Copying remote file '/preproc/t2m.hourly.1460.1140.01.2004.nc' to cache
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Opening input with Xarray Index({DimIndex(name='time', index=0, sequence_len=4, operation=<CombineOp.CONCAT: 2>), DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>)}): 'preproc/t2m.hourly.1460.1140.01.2004.nc'
pangeo_forge_recipes.storage - INFO - Opening 'preproc/t2m.hourly.1460.1140.01.2004.nc' from cache
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Caching metadata for input 'Index({DimIndex(name='time', index=0, sequence_len=4, operation=<CombineOp.CONCAT: 2>), DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>)})'
[....]
pangeo_forge_recipes.storage - INFO - Caching file 'preproc/tp.hourly.1460.1140.04.2004.nc'
pangeo_forge_recipes.storage - INFO - Copying remote file 'preproc/tp.hourly.1460.1140.04.2004.nc' to cache
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Opening input with Xarray Index({DimIndex(name='variable', index=1, sequence_len=2, operation=<CombineOp.MERGE: 1>), DimIndex(name='time', index=3, sequence_len=4, operation=<CombineOp.CONCAT: 2>)}): 'preproc/tp.hourly.1460.1140.04.2004.nc'
pangeo_forge_recipes.storage - INFO - Opening 'preproc/tp.hourly.1460.1140.04.2004.nc' from cache
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Caching metadata for input 'Index({DimIndex(name='variable', index=1, sequence_len=2, operation=<CombineOp.MERGE: 1>), DimIndex(name='time', index=3, sequence_len=4, operation=<CombineOp.CONCAT: 2>)})'
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Found an existing dataset in target

ValueError: Inconsistent sequence lengths between indices [1 3 0] of the concat dim.
Value(s) [696 720 696 720] at position(s) [(0, 1), (0, 3), (1, 1), (1, 3)] are different from the rest.
Please check the following file(s) for data errors:
- 'preproc/t2m.hourly.1460.1140.02.2004.nc'
- 'preproc/t2m.hourly.1460.1140.04.2004.nc'
- 'preproc/tp.hourly.1460.1140.02.2004.nc'
- 'preproc/tp.hourly.1460.1140.04.2004.nc'
[[744 696 744 720]
 [744 696 744 720]]
```

## Code

```python
import pandas as pd
import numpy as np
import os

import tempfile
from fsspec.implementations.local import LocalFileSystem
from pangeo_forge_recipes.patterns import ConcatDim, MergeDim, FilePattern
from pangeo_forge_recipes.recipes import XarrayZarrRecipe
from pangeo_forge_recipes.storage import FSSpecTarget, CacheFSSpecTarget, MetadataTarget, StorageConfig
from pangeo_forge_recipes.recipes import setup_logging

fs_local = LocalFileSystem()

target_dir = 'preproc/test.zarr'
target = FSSpecTarget(fs_local, target_dir)

cache_dir = tempfile.TemporaryDirectory()
cache_target = CacheFSSpecTarget(fs_local, cache_dir.name)

meta_dir = tempfile.TemporaryDirectory()
meta_store = MetadataTarget(fs_local, meta_dir.name)

store = StorageConfig(target=target, cache=cache_target, metadata=meta_store)

time = pd.date_range('2004-01-01', '2004-04-30', freq='MS')

FILE_FORMAT = (
    'preproc/{variable}.1460.1140.{time:%m}.{time:%Y}.nc'
)

def make_file(variable, time):
    return FILE_FORMAT.format(variable=variable, time=time)

time_concat_dim = ConcatDim('time', time)

variable_merge_dim = MergeDim('variable', keys=['t2m.hourly', 'tp.hourly'])

pattern = FilePattern(make_file, variable_merge_dim, time_concat_dim, file_type='netcdf3')

recipe = XarrayZarrRecipe(pattern, storage_config=store, cache_inputs=True, target_chunks={'time': 200, 'latitude': 40, 'longitude': 40})

setup_logging()

run_function = recipe.to_function()

run_function()

```

**Comment by cisaacstern** [comment]
@bask0 thanks for this question and for your interest in Pangeo Forge.

> "Inconsistent size of data in input files: This means we have to scan each input file and cache its metadata before we can start writing the target.'"

This quote from the docs is actually referring to inconsistencies in the length of files in the concat dimension. This is admittedly unclear based on the way this is phrased and we'd welcome a PR clarifying it.

Your issue appears in the merge dim: all of the files you are attempting to merge for a given variable are not of the same length. Specifically, it looks like the files 

    - 'preproc/t2m.hourly.1460.1140.02.2004.nc'
    - 'preproc/tp.hourly.1460.1140.02.2004.nc'

Do not have the same number of hourly time-steps? Is it the case, as suggested by the error, that one of these files comprises 696 hours whereas the other one comprises 720 hours?

If so, Pangeo Forge will not be able to merge them together. For two variables to be merged, their length in the concat dimension must be identical.

Please let me know if that helps clarify the situation, and how I can help move your recipe forward.

**Comment by bask0** [comment]
@cisaacstern thanks for having a look.

For concatenation, I guess that the variables must have the same time dimension _within_ months, right? Because this is the case. I compare the time dimensions of the variables per month and they seem to match exactly:

```python
import xarray as xr

for month in range(1, 13):
    a = xr.open_dataset(f'preproc/t2m.hourly.1460.1140.{month:02d}.2004.nc')
    b = xr.open_dataset(f'preproc/tp.hourly.1460.1140.{month:02d}.2004.nc')
    
    print(f'Month {month:02d}, {a.time.equals(b.time)=} ({len(a.time)=}, {len(b.time)=})')

# output >>>
Month 01, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 02, a.time.equals(b.time)=True (len(a.time)=696, len(b.time)=696)
Month 03, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 04, a.time.equals(b.time)=True (len(a.time)=720, len(b.time)=720)
Month 05, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 06, a.time.equals(b.time)=True (len(a.time)=720, len(b.time)=720)
Month 07, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 08, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 09, a.time.equals(b.time)=True (len(a.time)=720, len(b.time)=720)
Month 10, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)
Month 11, a.time.equals(b.time)=True (len(a.time)=720, len(b.time)=720)
Month 12, a.time.equals(b.time)=True (len(a.time)=744, len(b.time)=744)

```

Any suggestion or things I could test?

**Comment by cisaacstern** [comment]
This comparison is very helpful, thank you. And yes, it would appear this should not be raising an error.

@alxmrs made the last overhaul of this section of the code in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/255. Alex, I'm not completely up-to-speed with your approach there. Would you expect that logic to be able the current case, of ragged lengths in the concat dimension?

@bask0, something else you could do which would make this easier to debug would be one of the following:

- Put (a subset of) your input data somewhere where it is publicly accessible over HTTP

OR 

- Recreate this example using synthetic data generated with the `xarray.Dataset` interface. [This is how we create test data](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/e764542d05261a0b31916c61cc3afe2a96608b81/tests/conftest.py#L182-L208) for `pangeo-forge-recipes`. The datasets returned from a function like this can then be dumped to disk with `ds.to_netcdf()` and the recipe can be called on those synthetic files.

Either of these two options would allow us to work with the same data to debug this further. Please let me know if that makes sense, or if further guidance on either of those options would be useful.

**Comment by martindurant** [comment]
Note that kerchunk's "new" combine certainly *does* cope with the situation, as here, of uniform chunk sizes (24 hours per daily chunk) but different number of chunks per file. In fact, I feel like it may have been this very recipe that gave rise to having to make that change. Therefore, it may be possible to process via kerchunk even is direct pangeo-forge is failing.

**Comment by cisaacstern** [comment]
We should definitely be doing more work with kerchunk, and it's possible @bask0 may want to go that direction for this dataset, but just to clarify, if `XarrayZarrRecipe` is failing here, that is a bug which we should fix, not an architectural limitation.

**Comment by rabernat** [comment]
I agree that this looks like a bug. It means the logic in 

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/e764542d05261a0b31916c61cc3afe2a96608b81/pangeo_forge_recipes/recipes/xarray_zarr.py#L475-L494

is wrong.

Thanks very much @bask0 for raising this and helping us improve Pangeo Forge!

**Comment by bask0** [comment]
@cisaacstern I can reproduce with dummy date, see code below. I create random daily (because hourly not needed to reproduce) data for the year 2010, each month is in a separate file. There are two variables, `foo` and `bar` with pattern `dummydata.[foo, bar].[1, ..., 12].nc`

@martindurant I don't know what kerchunk does, but when I set `open_input_with_kerchunk=True` (if that is what you meant), I get another error, see below.

Warning: Executing the code will create the files in the current directory (but they are very small).

## Code

```python

import xarray as xr
import pandas as pd
import numpy as np
import tempfile
from fsspec.implementations.local import LocalFileSystem

from pangeo_forge_recipes.patterns import ConcatDim, MergeDim, FilePattern
from pangeo_forge_recipes.recipes import XarrayZarrRecipe
from pangeo_forge_recipes.storage import FSSpecTarget, CacheFSSpecTarget, MetadataTarget, StorageConfig
from pangeo_forge_recipes.recipes import setup_logging


def daily_xarray_dataset(start, end, varname):
    """Return a daily dummy xarray dataset from `start` to `end` date with variable name `varname`."""

    np.random.seed(1)
    ny, nx = 18, 36

    time = pd.date_range(start=start, end=end, freq="D")
    nt = len(time)
    lon = (np.arange(nx) + 0.5) * 360 / nx
    lon_attrs = {"units": "degrees_east", "long_name": "longitude"}
    lat = (np.arange(ny) + 0.5) * 180 / ny
    lat_attrs = {"units": "degrees_north", "long_name": "latitude"}
    foo = np.random.rand(nt, ny, nx)
    foo_attrs = {"long_name": "Fantastic Foo"}
    dims = ("time", "lat", "lon")
    ds = xr.Dataset(
        {varname: (dims, foo, foo_attrs)},
        coords={
            "time": ("time", time),
            "lat": ("lat", lat, lat_attrs),
            "lon": ("lon", lon, lon_attrs)},
        attrs={"conventions": "CF 1.6"},
    )
    return ds


# First and last day of each month in 2010.
M_start = pd.date_range(start="2010-01-01", periods=12, freq="MS")
M_end = pd.date_range(start="2010-01-01", periods=12, freq="M")

# Create datasets 'dummydata.[foo, bar].[1, ..., 12s].nc'
for var in ['foo', 'bar']:
    for i, (start, end) in enumerate(zip(M_start, M_end)):
        ds = daily_xarray_dataset(start, end, var)
        ds.to_netcdf(f'dummydata.{var}.{i + 1:02d}.nc')


fs_local = LocalFileSystem()

target_dir = 'test.zarr'
target = FSSpecTarget(fs_local, target_dir)

cache_dir = tempfile.TemporaryDirectory()
cache_target = CacheFSSpecTarget(fs_local, cache_dir.name)

meta_dir = tempfile.TemporaryDirectory()
meta_store = MetadataTarget(fs_local, meta_dir.name)

store = StorageConfig(target=target, cache=cache_target, metadata=meta_store)

time = pd.date_range('2004-01-01', '2004-12-31', freq='MS')

FILE_FORMAT = (
    'dummydata.{variable}.{time:%m}.nc'
)


def make_file(variable, time):
    return FILE_FORMAT.format(variable=variable, time=time)


time_concat_dim = ConcatDim('time', time)

variable_merge_dim = MergeDim('variable', keys=['foo', 'bar'])

pattern = FilePattern(make_file, variable_merge_dim, time_concat_dim)

recipe = XarrayZarrRecipe(
    pattern,
    storage_config=store,
    cache_inputs=True,
    target_chunks={'time': 10, 'lat': 4, 'lon': 4})

setup_logging()

run_function = recipe.to_function()

run_function()
```

## Error message

```
ValueError: Inconsistent sequence lengths between indices [1 3 0] of the concat dim.
Value(s) [28 30 30 30 30 28 30 30 30 30] at position(s) [(0, 1), (0, 3), (0, 5), (0, 8), (0, 10), (1, 1), (1, 3), (1, 5), (1, 8), (1, 10)] are different from the rest.
Please check the following file(s) for data errors:
- 'dummydata.foo.02.nc'
- 'dummydata.foo.04.nc'
- 'dummydata.foo.06.nc'
- 'dummydata.foo.09.nc'
- 'dummydata.foo.11.nc'
- 'dummydata.bar.02.nc'
- 'dummydata.bar.04.nc'
- 'dummydata.bar.06.nc'
- 'dummydata.bar.09.nc'
- 'dummydata.bar.11.nc'
[[31 28 31 30 31 30 31 31 30 31 30 31]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
```
## Error with `open_input_with_kerchunk=True`

```
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Caching input 'Index({DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>), DimIndex(name='time', index=0, sequence_len=12, operation=<CombineOp.CONCAT: 2>)})'
pangeo_forge_recipes.storage - INFO - Caching file 'dummydata.foo.01.nc'
pangeo_forge_recipes.storage - INFO - Copying remote file 'dummydata.foo.01.nc' to cache
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Opening input with Xarray Index({DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>), DimIndex(name='time', index=0, sequence_len=12, operation=<CombineOp.CONCAT: 2>)}): 'dummydata.foo.01.nc'
Traceback (most recent call last):
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/mapping.py", line 137, in __getitem__
    result = self.fs.cat(k)
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/spec.py", line 758, in cat
    return self.cat_file(paths[0], **kwargs)
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/spec.py", line 668, in cat_file
    with self.open(path, "rb", **kwargs) as f:
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/spec.py", line 1037, in open
    f = self._open(
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/implementations/local.py", line 159, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/implementations/local.py", line 254, in __init__
    self._open()
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/implementations/local.py", line 259, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/tmp/tmpcjby3hos/input-reference-time_0-variable_0.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Net/Groups/BGI/people/bkraft/drought_ml/preproc/pangeo_test.py", line 91, in <module>
    run_function()
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/pangeo_forge_recipes/executors/python.py", line 44, in function
    stage.function(m, config=pipeline.config)
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py", line 166, in cache_input
    with open_input(input_key, config=config) as ds:
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py", line 268, in open_input
    reference_data = config.storage_config.metadata[_input_reference_fname(input_key)]
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py", line 184, in __getitem__
    return json.loads(self.get_mapper()[key])
  File "/Net/Groups/BGI/people/bkraft/anaconda3/envs/dml/lib/python3.10/site-packages/fsspec/mapping.py", line 141, in __getitem__
    raise KeyError(key)
KeyError: 'input-reference-time_0-variable_0.json'
```

**Comment by rabernat** [comment]
Another comment: a short term workaround would be to make two separate recipes--one for `t2m` and the other for `tp`--and avoid the MergeDim. That should work.

**Comment by bask0** [comment]
Cool, thank you all very much and keep up the great work! For the `open_input_with_kerchunk` issue I think there is no need to follow up, I will try with two recipes.
