### ISSUE TITLE
Is the beam-refactor backwards compatible?

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-forge/pangeo-forge-recipes#439]
If I try to run a recipe with the beam-refactor branch as is, I get:

```
Parsing recipes...
Traceback (most recent call last):
  File "/Users/yuvipanda/.virtualenvs/staged-recipes/bin/pangeo-forge-runner", line 8, in <module>
    sys.exit(main())
  File "/Users/yuvipanda/code/pangeo-forge-runner/pangeo_forge_runner/cli.py", line 28, in main
    app.start()
  File "/Users/yuvipanda/code/pangeo-forge-runner/pangeo_forge_runner/cli.py", line 23, in start
    super().start()
  File "/Users/yuvipanda/.local/share/virtualenvs/staged-recipes/lib/python3.9/site-packages/traitlets/config/application.py", line 464, in start
    return self.subapp.start()
  File "/Users/yuvipanda/code/pangeo-forge-runner/pangeo_forge_runner/commands/bake.py", line 120, in start
    recipes = feedstock.parse_recipes()
  File "/Users/yuvipanda/code/pangeo-forge-runner/pangeo_forge_runner/feedstock.py", line 58, in parse_recipes
    recipes[r["id"]] = self._import(r["object"])
  File "/Users/yuvipanda/code/pangeo-forge-runner/pangeo_forge_runner/feedstock.py", line 43, in _import
    exec(compile(source=f.read(), filename=filename, mode="exec"), ns)
  File "recipes/daymet/recipe.py", line 9, in <module>
    from pangeo_forge_recipes.recipes import XarrayZarrRecipe
  File "/Users/yuvipanda/code/pangeo-forge-recipes/pangeo_forge_recipes/recipes/__init__.py", line 3, in <module>
    from .xarray_zarr import XarrayZarrRecipe
ModuleNotFoundError: No module named 'pangeo_forge_recipes.recipes.xarray_zarr'
```

I'm not exactly sure where this should come from instead. Is the refactor supposed to be backwards compatible? 

/cc @rabernat

**Comment by cisaacstern** [comment]
No, the `0.10.0` release (the first release post-beam-refactor) is _not_ backwards compatible. (I know you know that now, Yuvi, but noting for anyone else who may come across this.) Closing, thanks!
