### ISSUE TITLE
[beam-refactor] NetCDF + THREDDS Issue

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#511]
# Issue
I'm trying to use the `beam-refactor` branch to create a recipe for a Global Met Forcing dataset at NCAR. I'm interested in the `0.25deg Daily Means` for three variables. There are a few ways to access this data, in this example, the urls are being hosted by a THREDDS server. 

With the help of @cisaacstern, I've tried a few different approaches (specifying file_type in `Pattern()`, adding a cache etc.), but keep running into errors on the `OpenWithXarray` step of the pipeline.

A single url can be loaded successfully with `xarray`:

```python
import xarray as xr
ds = xr.open_dataset('https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/shum_0p25_daily_1948-1948.nc')

```

<img width="715" alt="image" src="https://user-images.githubusercontent.com/22455466/233226375-ac0b691f-e2bd-4817-a0a5-fa93323177a9.png">

### MRE

```python

import apache_beam as beam
from pangeo_forge_recipes.transforms import OpenURLWithFSSpec, OpenWithXarray, StoreToZarr
import os
from tempfile import TemporaryDirectory
from pangeo_forge_recipes.patterns import pattern_from_file_sequence

# Generate URLS
start_year = 1948
end_year = 1949
variables = ["shum", "tmin", "tmax"]

def gen_urls(start_year: int, end_year: int, variables: list) -> list:
    year_range = range(start_year, end_year + 1)
    return [
        f"[https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/{var}_0p25_daily_{year}-{year}.nc](https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/%7Bvar%7D_0p25_daily_%7Byear%7D-%7Byear%7D.nc)"
        for year in year_range
        for var in variables
    ]

url_list = gen_urls(start_year, end_year, variables)

# Create File Pattern
pattern = pattern_from_file_sequence(url_list, "time", nitems_per_file=1, file_type='netcdf4')

# Create Target Store Path
td = TemporaryDirectory()
target_root = td.name
store_name = "output.zarr"
target_store = os.path.join(target_root, store_name)

# Create Beam Pipeline
transforms = (
    beam.Create(pattern.items())
#    | OpenURLWithFSSpec()
    | OpenWithXarray(file_type=pattern.file_type, xarray_open_kwargs=dict(decode_times=True))

)


with beam.Pipeline() as p:
    p | transforms

```

```python KeyError: [<class 'h5netcdf.core.File'>, ('https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/shum_0p25_daily_1948-1948.nc',), 'r', (('decode_vlen_strings', True), ('invalid_netcdf', None)), '31e4ae5f-9b9a-4aba-b9b2-193e888a86ec']```

Traceback:
<details>

```python
Traceback (most recent call last):
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 210, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/shum_0p25_daily_1948-1948.nc',), 'r', (('decode_vlen_strings', True), ('invalid_netcdf', None)), '31e4ae5f-9b9a-4aba-b9b2-193e888a86ec']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 838, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 984, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/transforms/core.py", line -1, in <lambda>
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/pangeo_forge_recipes/transforms.py", line -1, in wrapper
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/pangeo_forge_recipes/openers.py", line 134, in open_with_xarray
    ds = xr.open_dataset(url_or_file_obj, **kw)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/api.py", line 526, in open_dataset
    backend_ds = backend.open_dataset(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 405, in open_dataset
    store = H5NetCDFStore.open(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 169, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 120, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 180, in ds
    return self._acquire()
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 172, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 198, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 216, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/h5netcdf/core.py", line 1035, in __init__
    raise ImportError(
ImportError: No module named 'h5pyd'. h5pyd is required for opening urls: https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/shum_0p25_daily_1948-1948.nc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/mb/7d7yq_4j2qgdfm_j3j4tsyl40000gn/T/ipykernel_67649/1176484966.py", line 1, in <module>
    with beam.Pipeline() as p:
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/pipeline.py", line 600, in __exit__
    self.result = self.run()
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/pipeline.py", line 577, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 202, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 224, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 455, in run_stages
    bundle_results = self._execute_bundle(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 783, in _execute_bundle
    self._run_bundle(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1012, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1348, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 379, in push
    response = self.worker.do_instruction(request)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/worker/sdk_worker.py", line 624, in do_instruction
    return getattr(self, request_type)(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/worker/sdk_worker.py", line 662, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1062, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/runners/worker/bundle_processor.py", line 232, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1420, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1492, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1582, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1695, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1420, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1492, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1582, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1695, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1420, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1492, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1582, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1695, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1420, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1508, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 838, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 984, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/apache_beam/transforms/core.py", line -1, in <lambda>
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/pangeo_forge_recipes/transforms.py", line -1, in wrapper
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/pangeo_forge_recipes/openers.py", line 134, in open_with_xarray
    ds = xr.open_dataset(url_or_file_obj, **kw)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/api.py", line 526, in open_dataset
    backend_ds = backend.open_dataset(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 405, in open_dataset
    store = H5NetCDFStore.open(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 169, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 120, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 180, in ds
    return self._acquire()
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 172, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 198, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 216, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/h5netcdf/core.py", line 1035, in __init__
    raise ImportError(
ImportError: No module named 'h5pyd'. h5pyd is required for opening urls: https://rda.ucar.edu/thredds/dodsC/files/g/ds314.0/0.25deg/daily/shum_0p25_daily_1948-1948.nc [while running '[9]: Create|OpenWithXarray/OpenWithXarray/Open with Xarray']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1052, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 978, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 878, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/IPython/core/ultratb.py", line 712, in lines
    return self._sd.lines
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/Users/nrhagen/opt/anaconda3/envs/install/envs/extreme-heat/lib/python3.10/site-packages/executing/executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

```
</details>

**Comment by rabernat** [comment]
This is fixed in #500.
